# Используем многоступенчатую сборку
FROM golang:1.25 AS builder

WORKDIR /app

# Копируем файлы модулей и загружаем зависимости
COPY ../../go.mod ../../go.sum ./
RUN go mod download

# Копируем весь код и собираем приложение
COPY ../../ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /my-subs ./cmd/my-subs

# Этап запуска
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Копируем бинарник из этапа builder
COPY --from=builder /my-subs .

# Команда для запуска
CMD ["./my-subs"]