package web

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/EgorLis/my-subs/internal/config"
	_ "github.com/EgorLis/my-subs/internal/docs" // docs generated by Swag CLI
	"github.com/EgorLis/my-subs/internal/domain"
	"github.com/EgorLis/my-subs/internal/transport/web/v1/health"
	"github.com/EgorLis/my-subs/internal/transport/web/v1/subscription"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Server struct {
	server *http.Server
	cfg    *config.Config
}

func New(cfg *config.Config, repo domain.SubscriptionRepository) *Server {
	healthHandler := &health.Handler{DBPinger: repo}
	subHandler := &subscription.Handler{Repo: repo}
	srv := &http.Server{
		Addr:              cfg.AppPort,
		Handler:           newRouter(healthHandler, subHandler),
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		MaxHeaderBytes:    1 << 20,
		ReadHeaderTimeout: 2 * time.Second,
		IdleTimeout:       60 * time.Second,
	}
	return &Server{server: srv, cfg: cfg}
}

func (ws *Server) Run() {
	log.Printf("server started on %s", ws.server.Addr)
	if err := ws.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("server error: %v", err)
	}
}

func (ws *Server) Close(ctx context.Context) {
	if err := ws.server.Shutdown(ctx); err != nil {
		log.Printf("server forced to shutdown: %v", err)
	}

	log.Println("server exited gracefully")
}

func newRouter(hh *health.Handler, sh *subscription.Handler) http.Handler {
	mux := http.NewServeMux()

	// health
	mux.HandleFunc("GET /healthz", hh.Liveness)
	mux.HandleFunc("GET /readyz", hh.Readiness)

	// subscriptions CRUDL
	mux.HandleFunc("POST /v1/subscriptions", limitBody(16<<10, sh.Create))     // 16 KB
	mux.HandleFunc("GET /v1/subscriptions", sh.List)                           // 16 KB
	mux.HandleFunc("PUT /v1/subscriptions/{id}", limitBody(16<<10, sh.Update)) // 16 KB
	mux.HandleFunc("DELETE /v1/subscriptions/{id}", sh.Delete)
	mux.HandleFunc("GET /v1/subscriptions/{id}", sh.Get)

	// swagger
	mux.Handle("GET /swagger/", httpSwagger.WrapHandler)

	loggedMux := loggingMiddleware(mux)

	return loggedMux
}

func limitBody(n int64, h http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		r.Body = http.MaxBytesReader(w, r.Body, n)
		h(w, r)
	}
}
